(function(scope) {
  "use strict";

  const STRINGS = Object.freeze({
    fr: Object.freeze({
      pinnedMessages: "Messages épinglés",
      pinned: "Épinglés",
      allMessages: "Tous les messages",
      panelScope: "Portée du panneau",
      selectedAccounts: "Comptes sélectionnés",
      scopeSelectedAccounts: "Comptes sélectionnés",
      sortPins: "Tri des épingles",
      currentInbox: "Cette boîte",
      currentAccount: "Ce compte",
      allAccounts: "Tous les comptes",
      manualOrder: "Ordre manuel",
      pinDate: "Épinglage",
      messageDate: "Date",
      deadline: "Échéance",
      priority: "Priorité",
      sender: "Expéditeur",
      account: "Compte",
      pinConversation: "Épingler la conversation sélectionnée",
      openDashboard: "Ouvrir le tableau de bord global",
      createGroup: "Créer un groupe",
      searchPins: "Rechercher dans les épingles…",
      searchPinsLabel: "Rechercher dans les messages épinglés",
      smartView: "Vue intelligente",
      readUnread: "Lu/non lu",
      complete: "Terminer",
      noReply: "Relancer sans réponse",
      archive: "Archiver",
      group: "Grouper",
      unpin: "Désépingler",
      delete: "Supprimer",
      pinMessage: "Épingler le message",
      unpinMessage: "Désépingler le message",
      moreActions: "Plus d’actions",
      cardActions: "Actions du message épinglé",
      openMessage: "Ouvrir le message",
      reply: "Répondre",
      markReadUnread: "Marquer lu / non lu",
      waiting: "Mettre en attente",
      planned: "Planifier",
      markComplete: "Marquer comme terminé",
      assignGroup: "Classer dans un groupe",
      trackNoReply: "Me relancer si aucune réponse",
      cancelNoReply: "Arrêter le suivi sans réponse",
      snoozeOneHour: "Reporter le rappel d’une heure",
      calendarTask: "Créer ou synchroniser une tâche",
      calendarEvent: "Créer ou synchroniser un événement",
      editFollowUp: "Modifier le suivi",
      noPinned: "Aucun message épinglé",
      noResult: "Aucun résultat",
      expandPinned: "Développer la section Épinglés",
      collapsePinned: "Réduire la section Épinglés",
      selectCalendarTask: "Choisir le calendrier de la tâche",
      selectCalendarEvent: "Choisir le calendrier de l’événement",
      calendarTarget: "Calendrier cible",
      cancel: "Annuler",
      continue: "Continuer",
      healthAttention: "Santé MailPerch à vérifier",
      healthHealthy: "Santé MailPerch correcte",
      calendarWriteAllowed: "écriture autorisée selon les vérifications locales",
      calendarStateUnknown: "état inconnu",
      calendarWriteRefused: "Écriture Agenda refusée",
      calendarUnknown: "inconnu",
      calendarWriteFailed: "Impossible d’écrire {label} dans le calendrier « {calendar} ». État détecté : {state}. Vérifiez les droits, la lecture seule, la synchronisation et les capacités du fournisseur, puis choisissez un autre calendrier. Le détail technique est disponible dans le diagnostic local.",
      caseCalendarTitleRequired: "Saisissez le titre de l’affaire avant de créer un élément Agenda.",
      caseCalendarDueRequired: "Saisissez une date et une heure avant de créer l’élément Agenda.",
      caseCalendarSelectionRequired: "Choisissez un calendrier compatible avant de créer l’élément Agenda.",
      panelToggleLabel: "Épinglés",
      panelHideSection: "Masquer la section Épinglés",
      panelShowSection: "Afficher la section Épinglés",
      panelUndo: "Annuler",
      panelEditFollowUpTitle: "Modifier le suivi",
      panelPersonalNote: "Note personnelle",
      panelChecklistTitle: "Sous-tâches",
      panelChecklistPlaceholder: "Ajouter une sous-tâche…",
      panelChecklistAdd: "Ajouter",
      panelChecklistRemove: "Supprimer la sous-tâche",
      panelChecklistProgress: "{completed}/{total} sous-tâches terminées",
      panelWaitingForThem: "J’attends une réponse",
      panelNeedsReply: "Je dois répondre",
      panelGroupLabel: "Groupe",
      panelCaseLabel: "Affaire",
      panelTemplateLabel: "Modèle de suivi",
      panelStatusLabel: "Statut",
      panelPriorityLabel: "Priorité",
      panelDeadlineLabel: "Échéance",
      panelReminderLabel: "Rappel",
      panelFollowUpLabel: "Relance / reprise",
      panelReminderRepeatLabel: "Répétition du rappel",
      panelRecurringLabel: "Suivi récurrent",
      panelRecurrenceIntervalLabel: "Intervalle de récurrence",
      panelAdvanceReminderLabel: "Rappel anticipé (minutes)",
      panelCalendarLabel: "Calendrier Agenda",
      panelMarkedComplete: "Marqué comme terminé",
      panelApplyTemplate: "Appliquer le modèle",
      panelSnooze10: "Reporter 10 min",
      panelSnoozeHour: "Reporter 1 h",
      panelSnoozeTomorrow: "Reporter à demain",
      panelSave: "Enregistrer",
      panelCancel: "Annuler",
      panelWorkflowActive: "À traiter",
      panelWorkflowWaiting: "En attente d’une réponse",
      panelWorkflowPlanned: "Planifié",
      panelWorkflowCompleted: "Terminé",
      panelPriorityNormal: "Normale",
      panelPriorityHigh: "Haute",
      panelPriorityUrgent: "Urgente",
      panelNone: "Aucune",
      panelRepeatDaily: "Chaque jour",
      panelRepeatWeekdays: "Jours ouvrés",
      panelRepeatWeekly: "Chaque semaine",
      panelRepeatMonthly: "Chaque mois",
      panelRecurrenceDaily: "Quotidienne",
      panelRecurrenceWeekdays: "Jours ouvrés",
      panelRecurrenceWeekly: "Hebdomadaire",
      panelRecurrenceMonthly: "Mensuelle",
      panelRecurrenceQuarterly: "Trimestrielle",
      panelRecurrenceYearly: "Annuelle",
      panelTemplateApplied: "Modèle de suivi appliqué.",
      panelEventSynced: "Événement créé ou synchronisé dans l’Agenda.",
      panelTaskSynced: "Tâche créée ou synchronisée dans l’Agenda.",
      panelCalendarFailed: "L’opération Agenda a échoué.",
      panelConversationPrefix: "Conversation · ",
      panelNoSubject: "(sans objet)",
      panelNoGroup: "Aucun groupe",
      panelNoCase: "Aucune affaire",
      panelNoTemplate: "Aucun modèle",
      panelCalendarTasks: "tâches",
      panelCalendarEvents: "événements",
      panelCreateGroupTitle: "Créer un groupe",
      panelGroupName: "Nom du groupe",
      panelColor: "Couleur",
      panelCreate: "Créer",
      panelGroupCreated: "Groupe créé.",
      panelMaxGroups: "Nombre maximal de groupes atteint.",
      panelDefaultGroupName: "À traiter",
      panelAssignMessages: "Classer les messages",
      panelApply: "Appliquer",
      panelMessagesAssigned: "{count} message(s) classé(s).",
      panelNoCompatibleEventCalendar: "Aucun calendrier inscriptible compatible avec un événement n’est disponible.",
      panelNoCompatibleTaskCalendar: "Aucun calendrier inscriptible compatible avec une tâche n’est disponible.",
      panelChooseEventCalendar: "Choisir le calendrier de l’événement",
      panelChooseTaskCalendar: "Choisir le calendrier de la tâche",
      panelCalendarChooserHelp: "Les calendriers incompatibles restent visibles pour expliquer pourquoi ils ne peuvent pas être utilisés.",
      panelTargetCalendar: "Calendrier cible",
      panelCalendarCompatible: "compatible",
      panelEventsUnsupported: "événements non pris en charge",
      panelTasksUnsupported: "tâches non prises en charge",
      panelMarkUnread: "Marquer comme non lu",
      panelMarkRead: "Marquer comme lu",
      panelReturnActive: "Repasser à traiter",
      panelSetWaiting: "Mettre en attente",
      panelPlan: "Planifier",
      panelReopen: "Rouvrir",
      panelMarkComplete: "Marquer comme terminé",
      panelEditNoReply: "Modifier la relance sans réponse",
      panelTrackNoReply: "Me relancer si aucune réponse",
      panelCancelNoReply: "Arrêter le suivi sans réponse",
      panelRemoveMissingReference: "Retirer la référence introuvable",
      panelRemoveFromGroup: "Retirer du groupe",
      panelRemoveFromNamedGroup: "Retirer du groupe « {group} »",
      panelMenuUnavailable: "Le menu d’actions est indisponible.",
      panelPinMissing: "Cette épingle n’existe plus.",
      panelMessageMissing: "Le message est introuvable.",
      panelUnpinned: "Message désépinglé.",
      panelMissingRemoved: "Référence introuvable retirée.",
      panelRemovedGroup: "Message retiré du groupe.",
      panelWaitingSuccess: "Message placé en attente.",
      panelActiveSuccess: "Message replacé à traiter.",
      panelPlannedSuccess: "Message planifié.",
      panelCompletedSuccess: "Message marqué comme terminé.",
      panelReopenedSuccess: "Message rouvert.",
      panelNoReplyScheduled: "Relance sans réponse prévue dans {days} jour(s).",
      panelNoReplyDisabled: "Suivi sans réponse désactivé.",
      panelReminderSnoozedHour: "Rappel reporté d’une heure.",
      panelCalendarCancelled: "Création Agenda annulée.",
      panelActionUnavailable: "Cette action ne peut pas être exécutée sur ce message.",
      panelReplyOpened: "Fenêtre de réponse ouverte.",
      panelActionFailed: "L’action n’a pas pu être exécutée.",
      panelDashboardOpening: "Ouverture du tableau de bord…",
      panelDashboardFailed: "Le tableau de bord n’a pas pu être ouvert. Redémarrez Thunderbird puis réessayez.",
      panelReminderUpdated: "Rappel mis à jour.",
      panelReminderFailed: "Le rappel n’a pas pu être mis à jour.",
      panelUndoCreateGroup: "Création du groupe",
      panelUndoBulkUnpin: "Désépinglage multiple",
      panelUndoPinConversation: "Épinglage de conversation",
      panelUndoUnpinConversation: "Désépinglage de conversation",
      panelUndoDragPin: "Épinglage par glisser-déposer",
      panelUndoChangeGroup: "Changement de groupe",
      panelUndoPin: "Épinglage",
      panelUndoUnpin: "Désépinglage",
      panelUnread: "Non lu",
      panelMissingAuthor: "Message introuvable",
      panelMovedOrDeleted: "Message déplacé ou supprimé",
      panelAriaCompleted: "Terminé",
      panelAriaMissing: "Message introuvable",
      panelMessagesCount: "{count} message(s)",
      panelUnreadCount: "{count} non lu(s)",
      panelOverdueCount: "{count} en retard",
      panelCompletedCount: "{count} terminé(s)",
      panelWaitingSince: "En attente depuis {date}",
      panelWaitingForReply: "En attente d’une réponse",
      panelPlanned: "Planifié",
      panelCompleted: "Terminé",
      panelFollowUpOverdue: "Relance en retard · {date}",
      panelFollowUpAt: "Relance · {date}",
      panelNoReplyOverdue: "Sans réponse · à relancer",
      panelNoReplyAt: "Sans réponse · {date}",
      panelRecurring: "Récurrent · {interval}{unit}",
      panelUnitDay: "jour",
      panelUnitWeekdays: "jours ouvrés",
      panelUnitWeek: "semaine",
      panelUnitMonth: "mois",
      panelUnitQuarter: "trimestre",
      panelUnitYear: "an",
      panelCaseChip: "Affaire · {name}",
      panelCalendarSynced: "Agenda synchronisé",
      panelOverdueAt: "En retard · {date}",
      panelDeadlineAt: "Échéance · {date}",
      panelPriorityHighChip: "Priorité haute",
      panelMessagePriorityHigh: "Priorité élevée du message",
      panelAttachment: "Pièce jointe",
      panelReply: "Répondre",
      panelSetWaitingForReply: "Mettre en attente d’une réponse",
      panelMarkCompletedQuick: "Marquer terminé",
      panelEditMetadata: "Note, affaire, modèle et échéance",
      panelSelectedCount: "{count} sélection(s)",
      panelHealthScore: "Santé {score}/100",
      panelHealthIssues: "{count} point(s) à vérifier dans le centre de santé",
      panelDisplayedCount: "{count} message(s) affiché(s).",
      panelLoadMore: "Afficher {count} message(s) de plus",
      panelSmartLater: "Plus tard",
      panelSmartCompleted: "Terminés",
      panelNoCustomGroup: "Sans groupe",
      panelBulkUnpinned: "{count} message(s) désépinglé(s).",
      panelBulkNoReply: "{count} suivi(s) sans réponse activé(s).",
      panelReminderCenter: "Rappels à traiter",
      panelOpen: "Ouvrir",
      panelDismiss: "Ignorer",
      reminderTitleFollowUp: "Relance à effectuer",
      reminderTitleOverdue: "Message épinglé en retard",
      reminderTitlePinned: "Rappel de message épinglé",
      calendarDisabledReason: "calendrier désactivé",
      calendarReadOnlyReason: "lecture seule",
      calendarAclDeniedReason: "droits d’écriture refusés par l’ACL",
      calendarItemsUnsupportedReason: "ni les tâches ni les événements ne sont pris en charge",
      calendarUnnamed: "Calendrier sans nom"
    }),
    en: Object.freeze({
      pinnedMessages: "Pinned messages",
      pinned: "Pinned",
      allMessages: "All messages",
      panelScope: "Panel scope",
      selectedAccounts: "Selected accounts",
      scopeSelectedAccounts: "Selected accounts",
      sortPins: "Sort pinned messages",
      currentInbox: "This inbox",
      currentAccount: "This account",
      allAccounts: "All accounts",
      manualOrder: "Manual order",
      pinDate: "Pinned date",
      messageDate: "Message date",
      deadline: "Deadline",
      priority: "Priority",
      sender: "Sender",
      account: "Account",
      pinConversation: "Pin the selected conversation",
      openDashboard: "Open the global dashboard",
      createGroup: "Create a group",
      searchPins: "Search pinned messages…",
      searchPinsLabel: "Search pinned messages",
      smartView: "Smart view",
      readUnread: "Read/unread",
      complete: "Complete",
      noReply: "Follow up if unanswered",
      archive: "Archive",
      group: "Group",
      unpin: "Unpin",
      delete: "Delete",
      pinMessage: "Pin message",
      unpinMessage: "Unpin message",
      moreActions: "More actions",
      cardActions: "Pinned message actions",
      openMessage: "Open message",
      reply: "Reply",
      markReadUnread: "Mark read/unread",
      waiting: "Set waiting",
      planned: "Plan",
      markComplete: "Mark complete",
      assignGroup: "Assign to a group",
      trackNoReply: "Remind me if there is no reply",
      cancelNoReply: "Stop no-reply tracking",
      snoozeOneHour: "Snooze reminder for one hour",
      calendarTask: "Create or sync a task",
      calendarEvent: "Create or sync an event",
      editFollowUp: "Edit follow-up",
      noPinned: "No pinned messages",
      noResult: "No results",
      expandPinned: "Expand Pinned section",
      collapsePinned: "Collapse Pinned section",
      selectCalendarTask: "Choose the task calendar",
      selectCalendarEvent: "Choose the event calendar",
      calendarTarget: "Target calendar",
      cancel: "Cancel",
      continue: "Continue",
      healthAttention: "MailPerch health needs attention",
      healthHealthy: "MailPerch health is good",
      calendarWriteAllowed: "write access is allowed by local checks",
      calendarStateUnknown: "unknown state",
      calendarWriteRefused: "Calendar write refused",
      calendarUnknown: "unknown",
      calendarWriteFailed: "Could not write {label} to calendar “{calendar}”. Detected state: {state}. Check permissions, read-only state, synchronization, and provider capabilities, then choose another calendar. The technical detail is available in the local diagnostic.",
      caseCalendarTitleRequired: "Enter the case title before creating a Calendar item.",
      caseCalendarDueRequired: "Enter a date and time before creating the Calendar item.",
      caseCalendarSelectionRequired: "Choose a compatible calendar before creating the Calendar item.",
      panelToggleLabel: "Pinned",
      panelHideSection: "Hide the Pinned section",
      panelShowSection: "Show the Pinned section",
      panelUndo: "Undo",
      panelEditFollowUpTitle: "Edit follow-up",
      panelPersonalNote: "Personal note",
      panelChecklistTitle: "Subtasks",
      panelChecklistPlaceholder: "Add a subtask…",
      panelChecklistAdd: "Add",
      panelChecklistRemove: "Remove subtask",
      panelChecklistProgress: "{completed}/{total} subtasks completed",
      panelWaitingForThem: "Waiting for their reply",
      panelNeedsReply: "I need to reply",
      panelGroupLabel: "Group",
      panelCaseLabel: "Case",
      panelTemplateLabel: "Follow-up template",
      panelStatusLabel: "Status",
      panelPriorityLabel: "Priority",
      panelDeadlineLabel: "Deadline",
      panelReminderLabel: "Reminder",
      panelFollowUpLabel: "Follow-up / resume",
      panelReminderRepeatLabel: "Reminder repeat",
      panelRecurringLabel: "Recurring follow-up",
      panelRecurrenceIntervalLabel: "Recurrence interval",
      panelAdvanceReminderLabel: "Advance reminder (minutes)",
      panelCalendarLabel: "Calendar",
      panelMarkedComplete: "Marked complete",
      panelApplyTemplate: "Apply template",
      panelSnooze10: "Snooze 10 min",
      panelSnoozeHour: "Snooze 1 hour",
      panelSnoozeTomorrow: "Snooze until tomorrow",
      panelSave: "Save",
      panelCancel: "Cancel",
      panelWorkflowActive: "Active",
      panelWorkflowWaiting: "Waiting for a reply",
      panelWorkflowPlanned: "Planned",
      panelWorkflowCompleted: "Completed",
      panelPriorityNormal: "Normal",
      panelPriorityHigh: "High",
      panelPriorityUrgent: "Urgent",
      panelNone: "None",
      panelRepeatDaily: "Every day",
      panelRepeatWeekdays: "Weekdays",
      panelRepeatWeekly: "Every week",
      panelRepeatMonthly: "Every month",
      panelRecurrenceDaily: "Daily",
      panelRecurrenceWeekdays: "Weekdays",
      panelRecurrenceWeekly: "Weekly",
      panelRecurrenceMonthly: "Monthly",
      panelRecurrenceQuarterly: "Quarterly",
      panelRecurrenceYearly: "Yearly",
      panelTemplateApplied: "Follow-up template applied.",
      panelEventSynced: "Event created or synchronized in Calendar.",
      panelTaskSynced: "Task created or synchronized in Calendar.",
      panelCalendarFailed: "The Calendar operation failed.",
      panelConversationPrefix: "Conversation · ",
      panelNoSubject: "(no subject)",
      panelNoGroup: "No group",
      panelNoCase: "No case",
      panelNoTemplate: "No template",
      panelCalendarTasks: "tasks",
      panelCalendarEvents: "events",
      panelCreateGroupTitle: "Create a group",
      panelGroupName: "Group name",
      panelColor: "Color",
      panelCreate: "Create",
      panelGroupCreated: "Group created.",
      panelMaxGroups: "Maximum number of groups reached.",
      panelDefaultGroupName: "To do",
      panelAssignMessages: "Assign messages",
      panelApply: "Apply",
      panelMessagesAssigned: "{count} message(s) assigned.",
      panelNoCompatibleEventCalendar: "No writable calendar compatible with an event is available.",
      panelNoCompatibleTaskCalendar: "No writable calendar compatible with a task is available.",
      panelChooseEventCalendar: "Choose the event calendar",
      panelChooseTaskCalendar: "Choose the task calendar",
      panelCalendarChooserHelp: "Incompatible calendars remain visible to explain why they cannot be used.",
      panelTargetCalendar: "Target calendar",
      panelCalendarCompatible: "compatible",
      panelEventsUnsupported: "events not supported",
      panelTasksUnsupported: "tasks not supported",
      panelMarkUnread: "Mark as unread",
      panelMarkRead: "Mark as read",
      panelReturnActive: "Return to active",
      panelSetWaiting: "Set waiting",
      panelPlan: "Plan",
      panelReopen: "Reopen",
      panelMarkComplete: "Mark as complete",
      panelEditNoReply: "Edit no-reply follow-up",
      panelTrackNoReply: "Remind me if there is no reply",
      panelCancelNoReply: "Stop no-reply tracking",
      panelRemoveMissingReference: "Remove missing reference",
      panelRemoveFromGroup: "Remove from group",
      panelRemoveFromNamedGroup: "Remove from “{group}”",
      panelMenuUnavailable: "The action menu is unavailable.",
      panelPinMissing: "This pin no longer exists.",
      panelMessageMissing: "The message cannot be found.",
      panelUnpinned: "Message unpinned.",
      panelMissingRemoved: "Missing reference removed.",
      panelRemovedGroup: "Message removed from group.",
      panelWaitingSuccess: "Message set to waiting.",
      panelActiveSuccess: "Message returned to active.",
      panelPlannedSuccess: "Message planned.",
      panelCompletedSuccess: "Message marked complete.",
      panelReopenedSuccess: "Message reopened.",
      panelNoReplyScheduled: "No-reply follow-up scheduled in {days} day(s).",
      panelNoReplyDisabled: "No-reply tracking disabled.",
      panelReminderSnoozedHour: "Reminder snoozed for one hour.",
      panelCalendarCancelled: "Calendar creation canceled.",
      panelActionUnavailable: "This action cannot be performed on this message.",
      panelReplyOpened: "Reply window opened.",
      panelActionFailed: "The action could not be completed.",
      panelDashboardOpening: "Opening the dashboard…",
      panelDashboardFailed: "The dashboard could not be opened. Restart Thunderbird and try again.",
      panelReminderUpdated: "Reminder updated.",
      panelReminderFailed: "The reminder could not be updated.",
      panelUndoCreateGroup: "Create group",
      panelUndoBulkUnpin: "Unpin multiple messages",
      panelUndoPinConversation: "Pin conversation",
      panelUndoUnpinConversation: "Unpin conversation",
      panelUndoDragPin: "Pin by drag and drop",
      panelUndoChangeGroup: "Change group",
      panelUndoPin: "Pin message",
      panelUndoUnpin: "Unpin message",
      panelUnread: "Unread",
      panelMissingAuthor: "Missing message",
      panelMovedOrDeleted: "Message moved or deleted",
      panelAriaCompleted: "Completed",
      panelAriaMissing: "Missing message",
      panelMessagesCount: "{count} message(s)",
      panelUnreadCount: "{count} unread",
      panelOverdueCount: "{count} overdue",
      panelCompletedCount: "{count} completed",
      panelWaitingSince: "Waiting since {date}",
      panelWaitingForReply: "Waiting for a reply",
      panelPlanned: "Planned",
      panelCompleted: "Completed",
      panelFollowUpOverdue: "Follow-up overdue · {date}",
      panelFollowUpAt: "Follow-up · {date}",
      panelNoReplyOverdue: "No reply · follow up now",
      panelNoReplyAt: "No reply · {date}",
      panelRecurring: "Recurring · {interval}{unit}",
      panelUnitDay: "day",
      panelUnitWeekdays: "weekdays",
      panelUnitWeek: "week",
      panelUnitMonth: "month",
      panelUnitQuarter: "quarter",
      panelUnitYear: "year",
      panelCaseChip: "Case · {name}",
      panelCalendarSynced: "Calendar synchronized",
      panelOverdueAt: "Overdue · {date}",
      panelDeadlineAt: "Deadline · {date}",
      panelPriorityHighChip: "High priority",
      panelMessagePriorityHigh: "High-priority message",
      panelAttachment: "Attachment",
      panelReply: "Reply",
      panelSetWaitingForReply: "Wait for a reply",
      panelMarkCompletedQuick: "Mark complete",
      panelEditMetadata: "Note, case, template, and deadline",
      panelSelectedCount: "{count} selected",
      panelHealthScore: "Health {score}/100",
      panelHealthIssues: "{count} item(s) need attention in the health center",
      panelDisplayedCount: "{count} message(s) displayed.",
      panelLoadMore: "Show {count} more message(s)",
      panelSmartLater: "Later",
      panelSmartCompleted: "Completed",
      panelNoCustomGroup: "No group",
      panelBulkUnpinned: "{count} message(s) unpinned.",
      panelBulkNoReply: "{count} no-reply follow-up(s) enabled.",
      panelReminderCenter: "Reminders to handle",
      panelOpen: "Open",
      panelDismiss: "Dismiss",
      reminderTitleFollowUp: "Follow-up due",
      reminderTitleOverdue: "Pinned message overdue",
      reminderTitlePinned: "Pinned message reminder",
      calendarDisabledReason: "calendar disabled",
      calendarReadOnlyReason: "read-only",
      calendarAclDeniedReason: "write access denied by ACL",
      calendarItemsUnsupportedReason: "neither tasks nor events are supported",
      calendarUnnamed: "Unnamed calendar"
    })
  });

  function language(locale) {
    return String(locale || "fr").toLowerCase().startsWith("en") ? "en" : "fr";
  }

  function interpolate(value, variables = {}) {
    return String(value || "").replace(/\{([a-zA-Z0-9_]+)\}/g, (_match, key) =>
      Object.prototype.hasOwnProperty.call(variables, key) ? String(variables[key]) : `{${key}}`
    );
  }

  function t(locale, key, fallback = "", variables = {}) {
    const lang = language(locale);
    return interpolate(STRINGS[lang]?.[key] || STRINGS.fr?.[key] || fallback || key, variables);
  }

  scope.PinLocalization = Object.freeze({STRINGS, language, interpolate, t});
})(this);
